Push images to Harbor
infobloxopen/farsight.collector.colo pull request #8
Opened 2020-12-21 13:02 UTC by i7tsov

2020-12-21 13:03 UTC, i7tsov commented
@tommyongib please open devops ticket to add this repo to https://github.com/orgs/Infoblox-CTO/teams/atlas-threatinsight team with write permission.

2020-12-21 13:04 UTC, i7tsov commented
@tommyongib please review.

2020-12-21 13:17 UTC, i7tsov commented
Please do not merge yet. I haven't identified Jenkins job that can push image for this repo.

2021-02-03 14:56 UTC, tgjonestx requested changes

2021-02-03 14:56 UTC, tgjonestx commented on Makefile
> +IMAGE_REGISTRY  ?= infobloxopen
Should be `infoblox`

2021-02-03 14:56 UTC, tgjonestx commented on Jenkinsfile
> +      finalizeBuild(imageList)
Remember that you need to run the harbor-repo-init job in Jenkins before the the first image can be pushed

2021-02-03 15:04 UTC, i7tsov commented on Jenkinsfile
> +      finalizeBuild(imageList)
Yeah, I've already created one in infobloxopen. Will create in infoblox now.

2021-02-03 15:16 UTC, i7tsov commented on Makefile
> +IMAGE_REGISTRY  ?= infobloxopen
Changed to `infoblox`.

2021-02-03 19:08 UTC, tgjonestx approved these changes

2021-02-03 20:54 UTC, tommyongib approved these changes

2021-02-04 15:40 UTC, merged